### ISSUE TITLE
[Bug] darkreader-lock meta tag broken in v4.9.86

### ISSUE THREAD

**Issue by HanPrower** [darkreader/darkreader#12809]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

The `darkreader-lock` metadata tag no longer seems to be obeyed on v4.9.86, but it works fine if I downgrade to v4.9.85.

### Website Address

https://bdcraft.net

### Steps To Reproduce

1. Make a website with the meta tag `darkreader-lock`
2. Visit website
3. Notice it doesn't obey the lock

### Expected Behavior

Lock is obeyed

### Actual Behavior

Lock is ignored

### Operating System

Arch Linux

### Web Browser name and version

Firefox v126.0.1

### Dark Reader version

4.9.86

**Comment by MeridianGH** [comment]
+1 Just observed the same. Thought I was going insane...

**Comment by Cohee1207** [comment]
Confirming. It caused some confusion among our users, specifically with Firefox. The meta tag is still there as you can see:

https://github.com/SillyTavern/SillyTavern/blob/f05d90bada1434fc540b733a6e04f231ed54ec3e/public/index.html#L10

**Comment by Cohee1207** [comment]
UPD: The issue seems to be introduced by this commit. https://github.com/darkreader/darkreader/commit/c49b8ad5afa3c8ed4e7bd21e120adab1964daf5c

Reverting it and rebuilding the extension seems to fix the issue in Firefox.

**Comment by HanPrower** [comment]
So after some prodding my guess is that at in the if statement on [Line 554](https://github.com/darkreader/darkreader/blob/main/src/inject/dynamic-theme/index.ts#L554)

We have a return, but not a "result". There's no `success();` or `failure();` so the dynamic theme is just applied instead. Adding a `failure();` before the return seems to resolve the issue, but I'm not sure if that's the correct way to fix it.

It is weird to me that if you enable/disable darkreader on a locked website it works then, just not on initial load...

@alexanderby As you authored the commit do you have any input on the issue? :)

**Comment by msr8** [comment]
+1

**Comment by HanPrower** [comment]
So I totally forgot about this, but I see there was [this commit](https://github.com/darkreader/darkreader/commit/77c92a5ae87882a7bab37e0de1ae8869508e61cb) to fix the issue.

From testing it seems to work, so I'll close this :smile_cat:
